document.getElementById("typo1").innerHTML = typeof 100;
document.getElementById("typo2").innerHTML = typeof 73.9;
document.getElementById("typo3").innerHTML = typeof NaN;
document.getElementById("typo4").innerHTML = typeof "water";
document.getElementById("typo5").innerHTML = typeof false;
document.getElementById("typo6").innerHTML = typeof 9 != 11;
document.getElementById("ora").innerHTML = "Orang" + "e";
document.getElementById("ora2").innerHTML = "Orange" - "s";
document.getElementById("four").innerHTML = "4" + "8";
document.getElementById("four2").innerHTML = "4" - "8";
document.getElementById("name+").innerHTML = "name" + 3;
document.getElementById("name-").innerHTML = "name" - 3;
document.getElementById("word").innerHTML = 82 * "word";
document.getElementById("hello").innerHTML = 1 + "hello";
document.getElementById("true").innerHTML = 1 + true;
document.getElementById("true2").innerHTML = "hello" + true;
document.getElementById("infin").innerHTML = typeof infinite;
document.getElementById("one1").innerHTML = 1 == '1';
document.getElementById("one2").innerHTML = 1 === '1';
